repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [--maxkb=100]
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format

  - repo: https://github.com/numpy/numpydoc
    rev: v1.7.0
    hooks:
      - id: numpydoc-validation

# --
# Hooks run in the order they are defined
# Use args: [] to pass additional arguments to hooks
# The args passed in here are only used when pre-commit is run, not when doing it manually
# See https://github.com/pre-commit/pre-commit-hooks for more hooks
# Supported 3rd party hooks: https://pre-commit.com/hooks.html
# Docstring validation using commit-hooks: https://numpydoc.readthedocs.io/en/latest/validation.html
# --
